INSERT INTO AUTHORITIES VALUES(2, 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES(3, 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES(4, 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES(5, 'ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES(6, 'ROLE_ADMIN');
